/* Generated by Yosys 0.52 (git sha1 fee39a3284c90249e1d9684cf6944ffbbcbb8f90) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/fifo.v:1.1-80.10" *)
module fifo(clk, rst, wr_en, rd_en, din, dout, full, empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/fifo_controller.v:0.0-0.0|rtl/fifo_controller.v:65.13-70.20|/usr/bin/../share/yosys/techmap.v:576.21-576.22" *)
  wire [3:0] _262_;
  (* src = "rtl/fifo.v:10.11-10.14" *)
  input clk;
  wire clk;
  (* hdlname = "controller clk" *)
  (* src = "rtl/fifo_controller.v:9.11-9.14" *)
  wire \controller.clk ;
  (* hdlname = "controller count" *)
  (* src = "rtl/fifo_controller.v:25.24-25.29" *)
  reg [3:0] \controller.count ;
  (* hdlname = "controller empty" *)
  (* src = "rtl/fifo_controller.v:19.12-19.17" *)
  wire \controller.empty ;
  (* hdlname = "controller full" *)
  (* src = "rtl/fifo_controller.v:18.12-18.16" *)
  wire \controller.full ;
  (* hdlname = "controller rd_en" *)
  (* src = "rtl/fifo_controller.v:13.11-13.16" *)
  wire \controller.rd_en ;
  (* hdlname = "controller rd_ptr" *)
  (* src = "rtl/fifo_controller.v:16.33-16.39" *)
  reg [2:0] \controller.rd_ptr ;
  (* hdlname = "controller read_en" *)
  (* src = "rtl/fifo_controller.v:22.12-22.19" *)
  wire \controller.read_en ;
  (* hdlname = "controller rst" *)
  (* src = "rtl/fifo_controller.v:10.11-10.14" *)
  wire \controller.rst ;
  (* hdlname = "controller wr_en" *)
  (* src = "rtl/fifo_controller.v:12.11-12.16" *)
  wire \controller.wr_en ;
  (* hdlname = "controller wr_ptr" *)
  (* src = "rtl/fifo_controller.v:15.33-15.39" *)
  reg [2:0] \controller.wr_ptr ;
  (* hdlname = "controller write_en" *)
  (* src = "rtl/fifo_controller.v:21.12-21.20" *)
  wire \controller.write_en ;
  (* src = "rtl/fifo.v:16.29-16.32" *)
  input [7:0] din;
  wire [7:0] din;
  (* src = "rtl/fifo.v:18.29-18.33" *)
  output [7:0] dout;
  wire [7:0] dout;
  (* src = "rtl/fifo.v:21.12-21.17" *)
  output empty;
  wire empty;
  (* src = "rtl/fifo.v:20.12-20.16" *)
  output full;
  wire full;
  (* hdlname = "memory clk" *)
  (* src = "rtl/fifo_memory.v:10.11-10.14" *)
  wire \memory.clk ;
  (* hdlname = "memory din" *)
  (* src = "rtl/fifo_memory.v:18.28-18.31" *)
  wire [7:0] \memory.din ;
  (* hdlname = "memory dout" *)
  (* src = "rtl/fifo_memory.v:20.33-20.37" *)
  reg [7:0] \memory.dout ;
  (* hdlname = "memory memory[0]" *)
  reg [7:0] \memory.memory[0] ;
  (* hdlname = "memory memory[1]" *)
  reg [7:0] \memory.memory[1] ;
  (* hdlname = "memory memory[2]" *)
  reg [7:0] \memory.memory[2] ;
  (* hdlname = "memory memory[3]" *)
  reg [7:0] \memory.memory[3] ;
  (* hdlname = "memory memory[4]" *)
  reg [7:0] \memory.memory[4] ;
  (* hdlname = "memory memory[5]" *)
  reg [7:0] \memory.memory[5] ;
  (* hdlname = "memory memory[6]" *)
  reg [7:0] \memory.memory[6] ;
  (* hdlname = "memory memory[7]" *)
  reg [7:0] \memory.memory[7] ;
  (* hdlname = "memory rd_addr" *)
  (* src = "rtl/fifo_memory.v:16.28-16.35" *)
  wire [2:0] \memory.rd_addr ;
  (* hdlname = "memory read_en" *)
  (* src = "rtl/fifo_memory.v:13.11-13.18" *)
  wire \memory.read_en ;
  (* hdlname = "memory wr_addr" *)
  (* src = "rtl/fifo_memory.v:15.28-15.35" *)
  wire [2:0] \memory.wr_addr ;
  (* hdlname = "memory write_en" *)
  (* src = "rtl/fifo_memory.v:12.11-12.19" *)
  wire \memory.write_en ;
  (* src = "rtl/fifo.v:14.11-14.16" *)
  input rd_en;
  wire rd_en;
  (* src = "rtl/fifo.v:28.27-28.33" *)
  wire [2:0] rd_ptr;
  (* src = "rtl/fifo.v:25.10-25.17" *)
  wire read_en;
  (* src = "rtl/fifo.v:11.11-11.14" *)
  input rst;
  wire rst;
  (* src = "rtl/fifo.v:13.11-13.16" *)
  input wr_en;
  wire wr_en;
  (* src = "rtl/fifo.v:27.27-27.33" *)
  wire [2:0] wr_ptr;
  (* src = "rtl/fifo.v:24.10-24.18" *)
  wire write_en;
  assign _079_ = ~\controller.count [0];
  assign _001_ = ~\controller.rd_ptr [0];
  assign _080_ = ~\controller.wr_ptr [2];
  assign _004_ = ~\controller.wr_ptr [0];
  assign _081_ = ~(\controller.count [1] | \controller.count [0]);
  assign _082_ = _081_ & ~(\controller.count [2]);
  assign _083_ = ~(\controller.count [2] ^ _081_);
  assign empty = _082_ & ~(\controller.count [3]);
  assign \controller.read_en  = rd_en & ~(empty);
  assign full = \controller.count [3] & _082_;
  assign \controller.write_en  = wr_en & ~(full);
  assign _084_ = \controller.write_en  | ~(\controller.read_en );
  assign _085_ = ~_084_;
  assign _086_ = _083_ | _084_;
  assign _087_ = \controller.count [1] & \controller.count [0];
  assign _088_ = \controller.count [2] | _087_;
  assign _089_ = \controller.write_en  & ~(\controller.read_en );
  assign _090_ = ~(\controller.count [2] & _087_);
  assign _091_ = _089_ & _090_;
  assign _092_ = ~(_088_ & _091_);
  assign _262_[2] = ~(_086_ & _092_);
  assign _093_ = ~(_081_ | _087_);
  assign _262_[1] = _093_ ? _089_ : _085_;
  assign _000_ = _085_ | _089_;
  assign _262_[0] = _079_ & _000_;
  assign _094_ = \controller.wr_ptr [1] & \controller.wr_ptr [0];
  assign _095_ = ~(\controller.wr_ptr [1] | \controller.wr_ptr [0]);
  assign _005_ = ~(_094_ | _095_);
  assign _096_ = \controller.rd_ptr [1] & ~(\controller.rd_ptr [0]);
  assign _002_ = \controller.rd_ptr [1] ^ \controller.rd_ptr [0];
  assign _097_ = ~(_082_ | _084_);
  assign _098_ = _089_ & ~(_090_);
  assign _099_ = _091_ | _097_;
  assign _262_[3] = \controller.count [3] ? _099_ : _098_;
  assign _100_ = \controller.wr_ptr [2] & \controller.write_en ;
  assign _101_ = \controller.wr_ptr [1] & \controller.write_en ;
  assign _102_ = ~(_094_ & _100_);
  assign _077_ = _102_ ? \memory.memory[7] [6] : din[6];
  assign _076_ = _102_ ? \memory.memory[7] [5] : din[5];
  assign _075_ = _102_ ? \memory.memory[7] [4] : din[4];
  assign _074_ = _102_ ? \memory.memory[7] [3] : din[3];
  assign _073_ = _102_ ? \memory.memory[7] [2] : din[2];
  assign _072_ = _102_ ? \memory.memory[7] [1] : din[1];
  assign _071_ = _102_ ? \memory.memory[7] [0] : din[0];
  assign _103_ = \controller.rd_ptr [0] ? \memory.memory[5] [6] : \memory.memory[4] [6];
  assign _104_ = \controller.rd_ptr [1] | ~(_103_);
  assign _105_ = ~(\memory.memory[6] [6] & _096_);
  assign _106_ = \controller.rd_ptr [1] & \controller.rd_ptr [0];
  assign _107_ = ~(\memory.memory[7] [6] & _106_);
  assign _108_ = \controller.rd_ptr [0] ? \memory.memory[1] [6] : \memory.memory[0] [6];
  assign _109_ = \controller.rd_ptr [1] | ~(_108_);
  assign _110_ = ~(\memory.memory[2] [6] & _096_);
  assign _111_ = ~(\memory.memory[3] [6] & _106_);
  assign _112_ = _110_ & _111_;
  assign _113_ = ~(_109_ & _112_);
  assign _114_ = _105_ & _107_;
  assign _115_ = ~(_104_ & _114_);
  assign _013_ = \controller.rd_ptr [2] ? _115_ : _113_;
  assign _116_ = \controller.rd_ptr [0] ? \memory.memory[1] [5] : \memory.memory[0] [5];
  assign _117_ = \controller.rd_ptr [1] | ~(_116_);
  assign _118_ = ~(\memory.memory[3] [5] & _106_);
  assign _119_ = \memory.memory[2] [5] & _096_;
  assign _120_ = ~(\controller.rd_ptr [2] | _119_);
  assign _121_ = _117_ & _120_;
  assign _122_ = ~(_118_ & _121_);
  assign _123_ = \controller.rd_ptr [0] ? \memory.memory[5] [5] : \memory.memory[4] [5];
  assign _124_ = \controller.rd_ptr [1] | ~(_123_);
  assign _125_ = ~(\memory.memory[6] [5] & _096_);
  assign _126_ = ~(\memory.memory[7] [5] & _106_);
  assign _127_ = \controller.rd_ptr [2] & _126_;
  assign _128_ = _124_ & _127_;
  assign _129_ = ~(_125_ & _128_);
  assign _012_ = _122_ & _129_;
  assign _130_ = \controller.rd_ptr [0] ? \memory.memory[1] [4] : \memory.memory[0] [4];
  assign _131_ = \controller.rd_ptr [1] | ~(_130_);
  assign _132_ = ~(\memory.memory[2] [4] & _096_);
  assign _133_ = \memory.memory[3] [4] & _106_;
  assign _134_ = ~(\controller.rd_ptr [2] | _133_);
  assign _135_ = _131_ & _134_;
  assign _136_ = ~(_132_ & _135_);
  assign _137_ = \controller.rd_ptr [0] ? \memory.memory[5] [4] : \memory.memory[4] [4];
  assign _138_ = \controller.rd_ptr [1] | ~(_137_);
  assign _139_ = ~(\memory.memory[6] [4] & _096_);
  assign _140_ = ~(\memory.memory[7] [4] & _106_);
  assign _141_ = _139_ & _140_;
  assign _142_ = \controller.rd_ptr [2] & _141_;
  assign _143_ = ~(_138_ & _142_);
  assign _011_ = _136_ & _143_;
  assign _144_ = \controller.rd_ptr [0] ? \memory.memory[1] [3] : \memory.memory[0] [3];
  assign _145_ = \controller.rd_ptr [1] | ~(_144_);
  assign _146_ = ~(\memory.memory[2] [3] & _096_);
  assign _147_ = \memory.memory[3] [3] & _106_;
  assign _148_ = ~(\controller.rd_ptr [2] | _147_);
  assign _149_ = _145_ & _148_;
  assign _150_ = ~(_146_ & _149_);
  assign _151_ = \controller.rd_ptr [0] ? \memory.memory[5] [3] : \memory.memory[4] [3];
  assign _152_ = \controller.rd_ptr [1] | ~(_151_);
  assign _153_ = ~(\memory.memory[7] [3] & _106_);
  assign _154_ = ~(\memory.memory[6] [3] & _096_);
  assign _155_ = \controller.rd_ptr [2] & _154_;
  assign _156_ = _152_ & _155_;
  assign _157_ = ~(_153_ & _156_);
  assign _010_ = _150_ & _157_;
  assign _158_ = \controller.rd_ptr [0] ? \memory.memory[5] [2] : \memory.memory[4] [2];
  assign _159_ = \controller.rd_ptr [1] | ~(_158_);
  assign _160_ = ~(\memory.memory[7] [2] & _106_);
  assign _161_ = ~(\memory.memory[6] [2] & _096_);
  assign _162_ = _159_ & _160_;
  assign _163_ = \controller.rd_ptr [2] & _162_;
  assign _164_ = ~(_161_ & _163_);
  assign _165_ = \controller.rd_ptr [0] ? \memory.memory[1] [2] : \memory.memory[0] [2];
  assign _166_ = \controller.rd_ptr [1] | ~(_165_);
  assign _167_ = \memory.memory[2] [2] & _096_;
  assign _168_ = ~(\memory.memory[3] [2] & _106_);
  assign _169_ = ~(\controller.rd_ptr [2] | _167_);
  assign _170_ = _166_ & _169_;
  assign _171_ = ~(_168_ & _170_);
  assign _009_ = _164_ & _171_;
  assign _172_ = \controller.rd_ptr [0] ? \memory.memory[5] [1] : \memory.memory[4] [1];
  assign _173_ = \controller.rd_ptr [1] | ~(_172_);
  assign _174_ = ~(\memory.memory[6] [1] & _096_);
  assign _175_ = ~(\memory.memory[7] [1] & _106_);
  assign _176_ = \controller.rd_ptr [2] & _175_;
  assign _177_ = _173_ & _176_;
  assign _178_ = ~(_174_ & _177_);
  assign _179_ = \controller.rd_ptr [0] ? \memory.memory[1] [1] : \memory.memory[0] [1];
  assign _180_ = \controller.rd_ptr [1] | ~(_179_);
  assign _181_ = \memory.memory[2] [1] & _096_;
  assign _182_ = ~(\memory.memory[3] [1] & _106_);
  assign _183_ = ~(\controller.rd_ptr [2] | _181_);
  assign _184_ = _180_ & _183_;
  assign _185_ = ~(_182_ & _184_);
  assign _008_ = _178_ & _185_;
  assign _186_ = \controller.rd_ptr [0] ? \memory.memory[5] [0] : \memory.memory[4] [0];
  assign _187_ = \controller.rd_ptr [1] | ~(_186_);
  assign _188_ = ~(\memory.memory[6] [0] & _096_);
  assign _189_ = ~(\memory.memory[7] [0] & _106_);
  assign _190_ = \controller.rd_ptr [2] & _188_;
  assign _191_ = _187_ & _190_;
  assign _192_ = ~(_189_ & _191_);
  assign _193_ = \controller.rd_ptr [0] ? \memory.memory[1] [0] : \memory.memory[0] [0];
  assign _194_ = \controller.rd_ptr [1] | ~(_193_);
  assign _195_ = ~(\memory.memory[3] [0] & _106_);
  assign _196_ = \memory.memory[2] [0] & _096_;
  assign _197_ = ~(\controller.rd_ptr [2] | _196_);
  assign _198_ = _194_ & _197_;
  assign _199_ = ~(_195_ & _198_);
  assign _007_ = _192_ & _199_;
  assign _200_ = _080_ & _095_;
  assign _201_ = ~(\controller.write_en  & _200_);
  assign _021_ = _201_ ? \memory.memory[0] [6] : din[6];
  assign _202_ = ~(\memory.memory[0] [5] & _201_);
  assign _203_ = din[5] & \controller.write_en ;
  assign _204_ = ~(_200_ & _203_);
  assign _020_ = ~(_202_ & _204_);
  assign _205_ = ~(\memory.memory[0] [4] & _201_);
  assign _206_ = din[4] & \controller.write_en ;
  assign _207_ = ~(_200_ & _206_);
  assign _019_ = ~(_205_ & _207_);
  assign _208_ = ~(\memory.memory[0] [3] & _201_);
  assign _209_ = din[3] & \controller.write_en ;
  assign _210_ = ~(_200_ & _209_);
  assign _018_ = ~(_208_ & _210_);
  assign _211_ = ~(\memory.memory[0] [2] & _201_);
  assign _212_ = din[2] & \controller.write_en ;
  assign _213_ = ~(_200_ & _212_);
  assign _017_ = ~(_211_ & _213_);
  assign _016_ = _201_ ? \memory.memory[0] [1] : din[1];
  assign _214_ = ~(\memory.memory[0] [0] & _201_);
  assign _215_ = din[0] & \controller.write_en ;
  assign _216_ = ~(_200_ & _215_);
  assign _015_ = ~(_214_ & _216_);
  assign _217_ = \controller.wr_ptr [0] & ~(\controller.wr_ptr [1]);
  assign _218_ = _080_ & _217_;
  assign _219_ = ~(\controller.write_en  & _218_);
  assign _029_ = _219_ ? \memory.memory[1] [6] : din[6];
  assign _028_ = _219_ ? \memory.memory[1] [5] : din[5];
  assign _220_ = ~(\memory.memory[1] [4] & _219_);
  assign _221_ = ~(_206_ & _218_);
  assign _027_ = ~(_220_ & _221_);
  assign _222_ = ~(\memory.memory[1] [3] & _219_);
  assign _223_ = ~(_209_ & _218_);
  assign _026_ = ~(_222_ & _223_);
  assign _224_ = ~(\memory.memory[1] [2] & _219_);
  assign _225_ = ~(_212_ & _218_);
  assign _025_ = ~(_224_ & _225_);
  assign _024_ = _219_ ? \memory.memory[1] [1] : din[1];
  assign _226_ = ~(\memory.memory[1] [0] & _219_);
  assign _227_ = ~(_215_ & _218_);
  assign _023_ = ~(_226_ & _227_);
  assign _228_ = ~(_004_ & _101_);
  assign _229_ = \controller.wr_ptr [2] | _228_;
  assign _037_ = _229_ ? \memory.memory[2] [6] : din[6];
  assign _036_ = _229_ ? \memory.memory[2] [5] : din[5];
  assign _035_ = _229_ ? \memory.memory[2] [4] : din[4];
  assign _034_ = _229_ ? \memory.memory[2] [3] : din[3];
  assign _033_ = _229_ ? \memory.memory[2] [2] : din[2];
  assign _032_ = _229_ ? \memory.memory[2] [1] : din[1];
  assign _031_ = _229_ ? \memory.memory[2] [0] : din[0];
  assign _230_ = _080_ & _094_;
  assign _231_ = ~(\controller.write_en  & _230_);
  assign _045_ = _231_ ? \memory.memory[3] [6] : din[6];
  assign _232_ = ~(\memory.memory[3] [5] & _231_);
  assign _233_ = ~(_203_ & _230_);
  assign _044_ = ~(_232_ & _233_);
  assign _234_ = ~(\memory.memory[3] [4] & _231_);
  assign _235_ = ~(_206_ & _230_);
  assign _043_ = ~(_234_ & _235_);
  assign _236_ = ~(\memory.memory[3] [3] & _231_);
  assign _237_ = ~(_209_ & _230_);
  assign _042_ = ~(_236_ & _237_);
  assign _041_ = _231_ ? \memory.memory[3] [2] : din[2];
  assign _040_ = _231_ ? \memory.memory[3] [1] : din[1];
  assign _238_ = ~(\memory.memory[3] [0] & _231_);
  assign _239_ = ~(_215_ & _230_);
  assign _039_ = ~(_238_ & _239_);
  assign _240_ = ~(_095_ & _100_);
  assign _053_ = _240_ ? \memory.memory[4] [6] : din[6];
  assign _052_ = _240_ ? \memory.memory[4] [5] : din[5];
  assign _051_ = _240_ ? \memory.memory[4] [4] : din[4];
  assign _050_ = _240_ ? \memory.memory[4] [3] : din[3];
  assign _049_ = _240_ ? \memory.memory[4] [2] : din[2];
  assign _048_ = _240_ ? \memory.memory[4] [1] : din[1];
  assign _047_ = _240_ ? \memory.memory[4] [0] : din[0];
  assign _241_ = ~(_100_ & _217_);
  assign _061_ = _241_ ? \memory.memory[5] [6] : din[6];
  assign _060_ = _241_ ? \memory.memory[5] [5] : din[5];
  assign _059_ = _241_ ? \memory.memory[5] [4] : din[4];
  assign _058_ = _241_ ? \memory.memory[5] [3] : din[3];
  assign _057_ = _241_ ? \memory.memory[5] [2] : din[2];
  assign _056_ = _241_ ? \memory.memory[5] [1] : din[1];
  assign _055_ = _241_ ? \memory.memory[5] [0] : din[0];
  assign _242_ = _080_ | _228_;
  assign _069_ = _242_ ? \memory.memory[6] [6] : din[6];
  assign _068_ = _242_ ? \memory.memory[6] [5] : din[5];
  assign _067_ = _242_ ? \memory.memory[6] [4] : din[4];
  assign _066_ = _242_ ? \memory.memory[6] [3] : din[3];
  assign _065_ = _242_ ? \memory.memory[6] [2] : din[2];
  assign _064_ = _242_ ? \memory.memory[6] [1] : din[1];
  assign _063_ = _242_ ? \memory.memory[6] [0] : din[0];
  assign _006_ = ~(_080_ ^ _094_);
  assign _003_ = \controller.rd_ptr [2] ^ _106_;
  assign _078_ = _102_ ? \memory.memory[7] [7] : din[7];
  assign _243_ = \controller.rd_ptr [0] ? \memory.memory[1] [7] : \memory.memory[0] [7];
  assign _244_ = \controller.rd_ptr [1] | ~(_243_);
  assign _245_ = ~(\memory.memory[2] [7] & _096_);
  assign _246_ = ~(\memory.memory[3] [7] & _106_);
  assign _247_ = _244_ & _246_;
  assign _248_ = ~(_245_ & _247_);
  assign _249_ = \controller.rd_ptr [2] | _248_;
  assign _250_ = \controller.rd_ptr [0] ? \memory.memory[5] [7] : \memory.memory[4] [7];
  assign _251_ = \controller.rd_ptr [1] | ~(_250_);
  assign _252_ = ~(\memory.memory[7] [7] & _106_);
  assign _253_ = ~(\memory.memory[6] [7] & _096_);
  assign _254_ = \controller.rd_ptr [2] & _253_;
  assign _255_ = _251_ & _254_;
  assign _256_ = ~(_252_ & _255_);
  assign _014_ = _249_ & _256_;
  assign _257_ = ~(\memory.memory[0] [7] & _201_);
  assign _258_ = din[7] & \controller.write_en ;
  assign _259_ = ~(_200_ & _258_);
  assign _022_ = ~(_257_ & _259_);
  assign _030_ = _219_ ? \memory.memory[1] [7] : din[7];
  assign _038_ = _229_ ? \memory.memory[2] [7] : din[7];
  assign _260_ = ~(\memory.memory[3] [7] & _231_);
  assign _261_ = ~(_230_ & _258_);
  assign _046_ = ~(_260_ & _261_);
  assign _054_ = _240_ ? \memory.memory[4] [7] : din[7];
  assign _062_ = _241_ ? \memory.memory[5] [7] : din[7];
  assign _070_ = _242_ ? \memory.memory[6] [7] : din[7];
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [0] <= _007_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [1] <= _008_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [2] <= _009_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [3] <= _010_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [4] <= _011_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [5] <= _012_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [6] <= _013_;
  always @(posedge clk)
    if (\controller.read_en ) \memory.dout [7] <= _014_;
  always @(posedge clk)
    \memory.memory[7] [0] <= _071_;
  always @(posedge clk)
    \memory.memory[7] [1] <= _072_;
  always @(posedge clk)
    \memory.memory[7] [2] <= _073_;
  always @(posedge clk)
    \memory.memory[7] [3] <= _074_;
  always @(posedge clk)
    \memory.memory[7] [4] <= _075_;
  always @(posedge clk)
    \memory.memory[7] [5] <= _076_;
  always @(posedge clk)
    \memory.memory[7] [6] <= _077_;
  always @(posedge clk)
    \memory.memory[7] [7] <= _078_;
  always @(posedge clk)
    \memory.memory[6] [0] <= _063_;
  always @(posedge clk)
    \memory.memory[6] [1] <= _064_;
  always @(posedge clk)
    \memory.memory[6] [2] <= _065_;
  always @(posedge clk)
    \memory.memory[6] [3] <= _066_;
  always @(posedge clk)
    \memory.memory[6] [4] <= _067_;
  always @(posedge clk)
    \memory.memory[6] [5] <= _068_;
  always @(posedge clk)
    \memory.memory[6] [6] <= _069_;
  always @(posedge clk)
    \memory.memory[6] [7] <= _070_;
  always @(posedge clk)
    \memory.memory[5] [0] <= _055_;
  always @(posedge clk)
    \memory.memory[5] [1] <= _056_;
  always @(posedge clk)
    \memory.memory[5] [2] <= _057_;
  always @(posedge clk)
    \memory.memory[5] [3] <= _058_;
  always @(posedge clk)
    \memory.memory[5] [4] <= _059_;
  always @(posedge clk)
    \memory.memory[5] [5] <= _060_;
  always @(posedge clk)
    \memory.memory[5] [6] <= _061_;
  always @(posedge clk)
    \memory.memory[5] [7] <= _062_;
  always @(posedge clk)
    \memory.memory[4] [0] <= _047_;
  always @(posedge clk)
    \memory.memory[4] [1] <= _048_;
  always @(posedge clk)
    \memory.memory[4] [2] <= _049_;
  always @(posedge clk)
    \memory.memory[4] [3] <= _050_;
  always @(posedge clk)
    \memory.memory[4] [4] <= _051_;
  always @(posedge clk)
    \memory.memory[4] [5] <= _052_;
  always @(posedge clk)
    \memory.memory[4] [6] <= _053_;
  always @(posedge clk)
    \memory.memory[4] [7] <= _054_;
  always @(posedge clk)
    \memory.memory[3] [0] <= _039_;
  always @(posedge clk)
    \memory.memory[3] [1] <= _040_;
  always @(posedge clk)
    \memory.memory[3] [2] <= _041_;
  always @(posedge clk)
    \memory.memory[3] [3] <= _042_;
  always @(posedge clk)
    \memory.memory[3] [4] <= _043_;
  always @(posedge clk)
    \memory.memory[3] [5] <= _044_;
  always @(posedge clk)
    \memory.memory[3] [6] <= _045_;
  always @(posedge clk)
    \memory.memory[3] [7] <= _046_;
  always @(posedge clk)
    \memory.memory[2] [0] <= _031_;
  always @(posedge clk)
    \memory.memory[2] [1] <= _032_;
  always @(posedge clk)
    \memory.memory[2] [2] <= _033_;
  always @(posedge clk)
    \memory.memory[2] [3] <= _034_;
  always @(posedge clk)
    \memory.memory[2] [4] <= _035_;
  always @(posedge clk)
    \memory.memory[2] [5] <= _036_;
  always @(posedge clk)
    \memory.memory[2] [6] <= _037_;
  always @(posedge clk)
    \memory.memory[2] [7] <= _038_;
  always @(posedge clk)
    \memory.memory[1] [0] <= _023_;
  always @(posedge clk)
    \memory.memory[1] [1] <= _024_;
  always @(posedge clk)
    \memory.memory[1] [2] <= _025_;
  always @(posedge clk)
    \memory.memory[1] [3] <= _026_;
  always @(posedge clk)
    \memory.memory[1] [4] <= _027_;
  always @(posedge clk)
    \memory.memory[1] [5] <= _028_;
  always @(posedge clk)
    \memory.memory[1] [6] <= _029_;
  always @(posedge clk)
    \memory.memory[1] [7] <= _030_;
  always @(posedge clk)
    \memory.memory[0] [0] <= _015_;
  always @(posedge clk)
    \memory.memory[0] [1] <= _016_;
  always @(posedge clk)
    \memory.memory[0] [2] <= _017_;
  always @(posedge clk)
    \memory.memory[0] [3] <= _018_;
  always @(posedge clk)
    \memory.memory[0] [4] <= _019_;
  always @(posedge clk)
    \memory.memory[0] [5] <= _020_;
  always @(posedge clk)
    \memory.memory[0] [6] <= _021_;
  always @(posedge clk)
    \memory.memory[0] [7] <= _022_;
  (* src = "rtl/fifo_controller.v:46.5-57.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.rd_ptr [0] <= 1'h0;
    else if (\controller.read_en ) \controller.rd_ptr [0] <= _001_;
  (* src = "rtl/fifo_controller.v:46.5-57.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.rd_ptr [1] <= 1'h0;
    else if (\controller.read_en ) \controller.rd_ptr [1] <= _002_;
  (* src = "rtl/fifo_controller.v:46.5-57.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.rd_ptr [2] <= 1'h0;
    else if (\controller.read_en ) \controller.rd_ptr [2] <= _003_;
  (* src = "rtl/fifo_controller.v:59.5-72.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.count [0] <= 1'h0;
    else if (_000_) \controller.count [0] <= _262_[0];
  (* src = "rtl/fifo_controller.v:59.5-72.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.count [1] <= 1'h0;
    else if (_000_) \controller.count [1] <= _262_[1];
  (* src = "rtl/fifo_controller.v:59.5-72.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.count [2] <= 1'h0;
    else if (_000_) \controller.count [2] <= _262_[2];
  (* src = "rtl/fifo_controller.v:59.5-72.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.count [3] <= 1'h0;
    else if (_000_) \controller.count [3] <= _262_[3];
  (* src = "rtl/fifo_controller.v:33.5-44.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.wr_ptr [0] <= 1'h0;
    else if (\controller.write_en ) \controller.wr_ptr [0] <= _004_;
  (* src = "rtl/fifo_controller.v:33.5-44.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.wr_ptr [1] <= 1'h0;
    else if (\controller.write_en ) \controller.wr_ptr [1] <= _005_;
  (* src = "rtl/fifo_controller.v:33.5-44.8" *)
  always @(posedge clk, posedge rst)
    if (rst) \controller.wr_ptr [2] <= 1'h0;
    else if (\controller.write_en ) \controller.wr_ptr [2] <= _006_;
  assign \controller.wr_en  = wr_en;
  assign \controller.rst  = rst;
  assign \controller.rd_en  = rd_en;
  assign \controller.full  = full;
  assign \controller.empty  = empty;
  assign \controller.clk  = clk;
  assign \memory.write_en  = \controller.write_en ;
  assign \memory.wr_addr  = \controller.wr_ptr ;
  assign \memory.read_en  = \controller.read_en ;
  assign \memory.rd_addr  = \controller.rd_ptr ;
  assign \memory.din  = din;
  assign \memory.clk  = clk;
  assign dout = \memory.dout ;
  assign rd_ptr = \controller.rd_ptr ;
  assign read_en = \controller.read_en ;
  assign wr_ptr = \controller.wr_ptr ;
  assign write_en = \controller.write_en ;
endmodule
